apiVersion: v1
kind: ConfigMap
metadata:
  name: yolo-config
  namespace: yolo
data:
  APP_ENV: "production"
  APP_LOG_LEVEL: "info"

---
apiVersion: v1
kind: Secret
metadata:
  name: yolo-secret
  namespace: yolo
type: Opaque
stringData:
  
  DB_USER: "root"
  DB_PASSWORD: "admin2023"
  DB_NAME: "yolodb"
