apiVersion: v1
kind: ConfigMap
metadata:
  name: yolo-backend-config
  namespace: yolo
data:
  PORT: "5000"

  # Mongo Replica Set URI
  MONGO_URI: "mongodb://root:admin2023@mongo-0.mongo.yolo.svc.cluster.local:27017,mongo-1.mongo.yolo.svc.cluster.local:27017,mongo-2.mongo.yolo.svc.cluster.local:27017/yolomy?replicaSet=rs0&authSource=admin"

  # Client (frontend) internal cluster address
  CLIENT_ORIGIN: "http://34.123.108.130"
