apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yolo-ingress
  namespace: yolo
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  rules:
  - host: yolo.example.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: yolo-web-lb
            port:
              number: 80
