apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: yolo
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "admin123"

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-mongo
  namespace: yolo
  labels:
    app: yolo-mongo
spec:
  ports:
    - port: 27017
      name: mongo
  clusterIP: None  # headless service
  selector:
    app: yolo-mongo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yolo-mongo
  namespace: yolo
spec:
  serviceName: "yolo-mongo"
  replicas: 1
  selector:
    matchLabels:
      app: yolo-mongo
  template:
    metadata:
      labels:
        app: yolo-mongo
    spec:
      containers:
        - name: mongo
          image: namanoo/naomi-yolo-mongodb:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              name: mongo
          envFrom:
            - secretRef:
                name: mongo-secret
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 10
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard
