apiVersion: v1
kind: Secret
metadata:
  name: yolo-secrets
  namespace: yolo
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "root"
  MONGO_ROOT_PASSWORD: "admin2023"
  JWT_SECRET: "CHANGEME_long_random"
